#ifndef __PISTACHIO_BUB_AUDIO_H
#define __PISTACHIO_BUB_AUDIO_H

#define PISTACHIO_DAUGHTERBOARD_NONE		0
#define PISTACHIO_DAUGHTERBOARD_CODEC		1
#define PISTACHIO_DAUGHTERBOARD_BREAKOUT	2
#define PISTACHIO_DAUGHTERBOARD_MAX		2

#define PISTACHIO_MCLK_NONE		0
#define PISTACHIO_MCLK_I2S		1
#define PISTACHIO_MCLK_DAC_CLK		2
#define PISTACHIO_MCLK_MAX		2

#endif
